# Generated by Django 5.1.6 on 2025-02-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaWebsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='pizzas',
        ),
        migrations.AddField(
            model_name='cart',
            name='pizzas',
            field=models.ManyToManyField(blank=True, null=True, to='pizzaWebsite.pizza'),
        ),
    ]
