# Generated by Django 5.1.6 on 2025-02-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaWebsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pizza',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
