# Generated by Django 5.1.6 on 2025-02-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaWebsite', '0002_remove_cart_pizzas_cart_pizzas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='pizzas',
            field=models.ManyToManyField(blank=True, to='pizzaWebsite.pizza'),
        ),
    ]
