# Generated by Django 5.1.6 on 2025-02-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaWebsite', '0002_cart_price_pizza_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
